### ISSUE TITLE
PR merge options: Squash and merge

### ISSUE THREAD

**Issue by vniclas** [opendr-eu/opendr#141]
Hi,

Can we somehow enforce the "squash and merge" option when merging a PR to master? This would greatly enhance the commit stream and remove all the unnecessary clutter, e.g.,

![squash_merge](https://user-images.githubusercontent.com/49001036/138418263-59ae2678-8f51-433a-8e0a-3e0163451b6e.png)

**Comment by vniclas** [comment]
Following up on this: @passalis, do you happen to know whether there is anyone else who has the required rights?

**Comment by passalis** [comment]
Settings have been updated to allow only for squash merging.
