### ISSUE TITLE
Create a submodule with ROS nodes only

### ISSUE THREAD

**Issue by thomaspeyrucain** [opendr-eu/opendr#143]
Have an easy to install submodule with only the ROS ready tools
It should be like a ROS package and if cloned inside the src folder of the catkin workspace; it should build successfully with catkin build command
Maybe we need to do this incrementally

**Comment by passalis** [comment]
Modular toolkit installation has probably addressed this, along with the docker images for various architectures. If there is indeed the need for more modularity can we re-open.
