### ISSUE TITLE
Missing/Incomplete Demos

### ISSUE THREAD

**Issue by passalis** [opendr-eu/opendr#169]
I have identified at least the following tools/tasks for which we do not provide any demo in projects:

**Perception:**
- [x] Speech recognition #188
   - [x] quadraticselfonn
   - [x] matchboxnet
   - [x] edgesspeechnets

**Planning:**
- [ ] End-to-End planner

**Comment by dHonerkamp** [comment]
Added a PR for the mobile manipulation demo: #170

**Comment by sisaha9** [comment]
@passalis What are the current considerations for the end to end planner?

**Comment by passalis** [comment]
There is a PR open #82 for this tool.

**Comment by passalis** [comment]
I am closing this, since there all demos have been integrated in the first version, apart from the end-to-end planner that will be part of the next release.
