### ISSUE TITLE
Compatibility with TX2 and Xavier?

### ISSUE THREAD

**Issue by LukasHedegaard** [opendr-eu/opendr#197]
Does the OpenDR library have a requirement for full compatibility with TX2 and Xavier? 
For instance, the activity recognition dataset Kinetics has a dependency on `av` in most open-source dataloaders, as well as in the OpenDR implementataion. However `av` cannot be installed on TX2. 

In this case, the question is whether the `av` library dependency should be removed completely (and the dataloader rewritten) or whether it is OK if some parts of the toolkit are useable with embedded hardware, while others (such as a dataloader for a dataset, that would never fit on TX2 disk space) are not?

**Comment by passalis** [comment]
@LukasHedegaard thanks for highlighting this. 

I think that we do not need to make training tools fully available for TX-2 and Xavier. In most practical scenarios that I can think of right now (and we have described as supported use cases), only inference is going to be needed on these platforms (apart from very specific tools, where part of the training pipeline might be needed - most probably only face recognition, where we might want to re-build the database).  In any case,  these devices are designed and optimized for inference and they are too weak to be used for any practical training using large-scale datasets (that do not even fit in their disk). 

So, having inference working correctly on these devices is indeed critical. Having training working is an added bonus (e.g., for niche applications), but most probably not required for any practical application.

I think a critical question here is how to correctly separate inference-only dependence from training/inference dependencies.  In #195 the requirements are manually installed, but perhaps we can find a way to automate this by adding some annotations or having separate dependecies.ini files/etc.
