### ISSUE TITLE
Installation when venv is not available

### ISSUE THREAD

**Issue by iliiliiliili** [opendr-eu/opendr#217]
If venv is not installed in the system (Jetson Xavier in my case), the installation goes on, but in the console output shows that venv is not created. Should it be either stopped, or notified that it will be installed directly?

**Comment by Pavlos-Tosidis** [comment]
[TX2_install.sh](https://github.com/opendr-eu/opendr/blob/tx2_install/bin/install_tx2.sh) is installing the toolkit directly on the system.

**Comment by Pavlos-Tosidis** [comment]
Closing this as #195 address this and the instructions are clear about venv not being needed for Nvidia's supported embedded systems.
