### ISSUE TITLE
ROS nodes delay

### ISSUE THREAD

**Issue by tsampazk** [opendr-eu/opendr#275]
### General Description
Some ROS nodes exhibit delay between the current frame and the frame that is being published.

### Cause
This is because in most (all?) nodes the subscriber which uses the callback that performs inference, has a `queue_size` of `10`. If the callback inference is slow, the subscriber keeps the incoming frames and processes them all one-by-one. When processing of one frame ends, the callback grabs an old frame from inside the queue and so on, causing the delay in the output.

### Expected behaviour and solution
The expected behaviour would be to process the newest, most update-to-date frame every time the callback grabs a frame for inference and not use older frames. This is done by setting the `queue_size` to `1`, but to properly work in ROS 1 you also need to set the `buffer_size` accordingly. I found that a value of `5000000` for the buffer size works well on object detection 2D. The delay is minimized to whatever time it takes for one frame to process which is expected.

Edit: ~~Some~~ All nodes require a larger buffer size to minimize delay, e.g. `10000000`.

Edit: **For ROS2 it is not required to set the buffer size, just add `1` as the queue size as seen [here](https://github.com/opendr-eu/opendr/blob/b9dab8c0764143d9817944851defa8502750a146/projects/opendr_ws_2/src/opendr_perception/opendr_perception/face_detection_retinaface_node.py#L53-L63).**

**Comment by tsampazk** [comment]
I'll document my understanding below for future reference. After the fixes you should expect a delay of 2 frames. This is because, as far as i can tell, **we have to work with a minimum buffer of size `1`**, plus the frame that was already being processed. In more detail:

![ROS_delay_diagram](https://user-images.githubusercontent.com/27914645/185743734-8f996c76-a376-4cd0-a703-6367a48f34f9.jpg)

At times `t`, `t + 1`, etc. processed frames are being published. Keep in mind that frames are coming in as fast as the camera being used allows. Irrelevant frames are omitted.

1. A **reference visible movement** starts at `tm` and is completed before `t + 1`, e.g. a subject person raised their hand quickly (movement is complete before `t + 1`) and holds it in position until `t + 1`. 
2. The critical frame `Fm` that shows the person with their hand raised is captured at `t+1` and is stored in the buffer (that's when `F2` is taken from the buffer to process and the buffer is empty). At the same time `F1` is published. 
3. `F2` is published at `t+2` and processing of `Fm` begins. 
4. Finally, `Fm` is published at `t+3` **with a total delay of the time it takes for 2 frames to process.**

**Comment by passalis** [comment]
I think this explains the expected behavior in a very nice way. We can perhaps mention this issue  in the documentation (or even move the diagram and explanation there).
