### ISSUE TITLE
Missing Docker images

### ISSUE THREAD

**Issue by tetsu** [opendr-eu/opendr#283]
It seems [OpenDR Docker images on Docker Hub](https://hub.docker.com/r/opendr/opendr) are missing. If you can upload docker images or provide dockerfiles on Github, it'll be really helpful. Thank you.

**Comment by ad-daniel** [comment]
Hi, the docker images are available here: https://hub.docker.com/r/opendr/opendr-toolkit

**Comment by passalis** [comment]
Hi, the docker images are available at https://hub.docker.com/r/opendr/opendr-toolkit while the dockerfiles are also available on the root of this repo (e.g., https://github.com/opendr-eu/opendr/blob/master/Dockerfile)
