### ISSUE TITLE
Change image in OpenCV format before saving in ROS1 simulation package

### ISSUE THREAD

**Issue by charsyme** [opendr-eu/opendr#292]
The following line should be changed to "cv2.imwrite('./rendering.png', out_imgs[0].opencv())"

https://github.com/opendr-eu/opendr/blob/3a9a119f2f4391c3d9ba5f2f998400ffb61f72cf/projects/opendr_ws/src/simulation/scripts/human_model_generation_client.py#L49

**Comment by passalis** [comment]
Hi @charsyme, thanks for catching this. Feel free to add this change to #291 if you wish.
