### ISSUE TITLE
Errors when testing tools 

### ISSUE THREAD

**Issue by AleaScovill** [opendr-eu/opendr#309]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/ALEASC~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DA link=blue vlink="#954F72" style='tab-interval:65.2pt;word-wrap:
break-word'>

List of tools | Object detection and tracking of   humans in the field | Scene understanding | Animal detection | Test output
-- | -- | -- | -- | --
rosrun perception fall_detection.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Output:   [INFO] [1663159449.682438, 167824.240000]: Fall detection node started!
rosrun perception pose_estimation.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Output:   [INFO] [1663159294.174351, 167687.850000]: Pose estimation node started!
rosrun perception object_tracking_2d_fair_mot.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Got this continuous output:   error in modulated_deformable_im2col_cuda: too many resources requested for   launch   error in modulated_deformable_im2col_cuda: too many resources requested for   launch   [INFO] [1663159159.210091, 167569.950000]: Published annotated image   [INFO] [1663159159.214582, 167569.950000]: Published detection boxes   [INFO] [1663159159.218589, 167569.950000]: Published tracking ids
rosrun perception object_tracking_2d_deep_sort.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x |   |   | Can’t find this part
rosrun perception object_detection_2d_ssd.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes/No - Not all scenario is detected.   Speed: 1.28 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_yolov3.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes   Speed: 1.44 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_centernet.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Detection: Yes - Multiple Bbox for 1 object.   Speed: 1.31 FPS (output) @ 4.76 FPS (input) - Moving   average size = 400
rosrun perception object_detection_2d_detr.py   _input_image_topic:=/vision/camera/cropeye3/image_raw | x | x | x | Didn’t output anything on the topic.   Last output on cmd:   [INFO] [1663158288.858492, 0.000000]: DETR node started!
rosrun perception semantic_segmentation_bisenet.py   _input_image_topic:=/vision/camera/cropeye3/image_raw |   | x |   | [FATAL] [1663158442.962755]: cannot register subscription topic   [/_input_image_topic:=/vision/camera/cropeye3/image_raw] with master: ERROR:   parameter [topic] contains illegal chars   [ERROR] [1663158442.969023]: Unable to immediately register with master node   [http://192.168.20.100:11311]:   master may not be running yet. Will keep trying.

</body>

</html>

**Comment by tsampazk** [comment]
Hey @AleaScovill! I have some questions and comments:
1. Are you testing the updated nodes from the `develop` branch or are you using the `master` branch?
2. From what i can tell, pose estimation, fall detection and object detection 2d yolov3 are running without any problems?
3. The basic way to modify the nodes would be through argparse, so to run a node with a custom input and output topic it would look like `rosrun perception pose_estimation.py -i my_input_topic -o my_output_topic`, and you can also refer to `rosrun perception pose_estimation.py -h` for more information
4. Even if you use the most recent nodes from the `develop` branch, some nodes might not be updated yet, please refer to the tracker issue #305

**Comment by AleaScovill** [comment]
Hi Kostas,


  1.  We are testing the docker - Not sure if it is develop or master. TX2_install is the branch. Docker version tx_2_v1.1
  2.  Yes
  3.  Thanks
  4.  Will the documentation be updated to reflect issue #305?


Best regards / Med venlig hilsen

Alea Scovill
R&D Manager

AGROINTELLI | Agro Food Park 13, Skejby | 8200 Aarhus N | Denmark | www.agrointelli.com<http://www.agrointelli.com/> | Mobile +45 6049 7299

**Comment by tsampazk** [comment]
Hey @AleaScovill, thanks for answering the questions!

> 1. We are testing the docker - Not sure if it is develop or master. TX2_install is the branch. Docker version tx_2_v1.1 

The docker image you are using is built from the master branch so it doesn't contain the latest updates of the nodes unfortunately.
We had a discussion with Pavlos regarding this today. We will investigate into building an image from the develop branch so you can test the most up-to-date nodes and other solutions which we can discuss in the next meeting.

> 4. Will the documentation be updated to reflect issue #305?

I'm currently in the process of overhauling the ROS [README file](https://github.com/opendr-eu/opendr/blob/develop/projects/opendr_ws/src/perception/README.md) to reflect the changes so far.
