### ISSUE TITLE
Problematic generation of 3D human models

### ISSUE THREAD

**Issue by charsyme** [opendr-eu/opendr#334]
Thank you for the fixes @charsyme ! There are some minor changes that are still needed and we should be good to go.

Regarding the error, i still got it when trying to run the node the `ros2-human-model-generation` branch. I reverted the line to the old version `marching_cubes_lewiner` instead of the current version `marching_cubes` (which also produces a warning `Cannot find reference 'marching_cubes' in '__init__.py | __init__.py' ` in my IDE). With the old version it runs without error, producing 2 images that i attach bellow. One of them seems problematic. However, we don't need to fix this to merge the PR, because it is not related to the ROS2 nodes. Could you investigate further and maybe open an issue to document the error if it is indeed present?

![rendering30](https://user-images.githubusercontent.com/27914645/191955336-35ac35e3-99f1-4476-8133-f938a9989550.jpg)
![rendering120](https://user-images.githubusercontent.com/27914645/191955339-57119238-8c3c-44a6-802a-c8b309ca0024.jpg)

_Originally posted by @tsampazk in https://github.com/opendr-eu/opendr/pull/291#pullrequestreview-1118237217_

**Comment by tsampazk** [comment]
I ran the nodes again and noticed that on the pop-up windows that show the produced images, both get produced properly. It's when i open the images that are saved locally that the glitched photo appears.
