### ISSUE TITLE
Several tools have deprecation warnings, especially those relying on numpy

### ISSUE THREAD

**Issue by ad-daniel** [opendr-eu/opendr#382]
As emerged here https://github.com/opendr-eu/opendr/pull/381 without the upper restriction on numpy, the version 1.24.0 might be installed and in it several deprecation warnings have expired.
Even when things work, several deprecation warnings are printed when running the tests. Both issues should be addressed.

**Comment by passalis** [comment]
We had several iterations of dependency updates, which should probably have addressed these issues as far as I understand.
