### ISSUE TITLE
`object detection 3d` and `object tracking 3d` tests are currently disabled

### ISSUE THREAD

**Issue by ad-daniel** [opendr-eu/opendr#395]
As discussed in the meeting, @iliiliiliili  currently the `object detection 3d` and `object tracking 3d` tests are disabled in the CI due to failures. 

The test itself passes, unittest seems to crash after it by throwing a `free(): invalid pointer` error. It happens consistently for these 2 tools, so I suspect it has to be related to the tools in question somehow.

What I attempted before:
- try/catch every sub-test but it doesn't appear to fail any of those
- tried to comment out parts of the test until the failure went away. I had to go as far as commenting out `from opendr.perception.object_detection_3d import VoxelObjectDetection3DLearner` for it to stop crashing so I suspect the problem is somewhere in the learner class itself (or in one of the classes it depends on). It was some time ago, you should re-check this

To reproduce the failure you need to set the `test release` label. I suggest you disable all other tests in the workflow and leave only these 2 active to speed up the debugging.

**Comment by ad-daniel** [comment]
also it should be noted, I was never able to reproduce it locally but it failed consistently in the CI. So perhaps the lack of GPU might have something to do with it

**Comment by passalis** [comment]
Probably cannot be easily fixed, since this is an issue on CI/github side. Manual testing will be performed for these two tools.
