### ISSUE TITLE
Python style tests do not support typing

### ISSUE THREAD

**Issue by iliiliiliili** [opendr-eu/opendr#42]
Source code:
```
self.data: List[BoundingBox3D] = bounding_boxes_3d
```

Command:
`python3 -m unittest discover -s tests/`

Result:
`target.py:193:18: E701: multiple statements on one line (colon)`

It sees the typing statement as an if/while/... with the body on the same line.

**Comment by dHonerkamp** [comment]
This is preventing the integration of #68 as well now. Is there a resolution?

**Comment by passalis** [comment]
I think that these difficulties have been resolved, so I am closing this for now.
