### ISSUE TITLE
Onnx Model Download

### ISSUE THREAD

**Issue by MarkJhonBao** [opendr-eu/opendr#475]
Hello:

Can the onnx weight used in CAPI be used now?

**Comment by MarkJhonBao** [comment]
??

**Comment by passalis** [comment]
Hi, specific tools are supported by the C API. You can find the list [here](https://github.com/opendr-eu/opendr/tree/master/projects/c_api).

**Comment by passalis** [comment]
If there is anything unclear in the documentation or API, we can re-open this issue to address any concerns.
