### ISSUE TITLE
References for Single Demo Grasp

### ISSUE THREAD

**Issue by lx704612715** [opendr-eu/opendr#500]
Dear Developer Team, 

I am curious if there are any reference papers available for the "Single Demo Grasp" project. I am asking because this project is closely related to my recent IROS paper, which can be found [here](https://www.static.tu.berlin/fileadmin/www/10002220/Publications/Li-2023-IROS.pdf). I am currently working on a follow-up paper and would like to compare and cite the reference papers of the aforementioned project.

Thank you!

**Comment by Zorrander** [comment]
Hi @lx704612715,

You can find the reference paper for this project at https://ieeexplore.ieee.org/document/9926463.
