### ISSUE TITLE
Tests are printing many warnings

### ISSUE THREAD

**Issue by stefaniapedrazzi** [opendr-eu/opendr#62]
The existing tests currently print lot of warning (cuda, UserWarning, DeprecationWarning, ResourceWarning) that make the logs hard to read.

We should try to fix all this warnings.
In case this won't be possible, the warnings should be filtered and not printed on the console when running the tests.

All the tests seems to print some warnings:
@Pavlos-Tosidis , @iliiliiliili , @jovaroo could you please double check your tests and fix or filter the warnings?

**Comment by passalis** [comment]
Tests have been revised to this end. We can reopen this issue if we observe excessive number of warning being printed out.
